### ISSUE TITLE
what‘s the meaning of the ADR ?

### ISSUE THREAD

**Issue by ucas010** [ljynlp/W2NER#87]
in the data/example 
**"type": "ADR"**

could you pls help me ?

**Comment by ucas010** [comment]
run the example got error 
python main.py --config ./config/example.json

2023-03-06 16:42:31 - INFO: Epoch: 0
Traceback (most recent call last):
  File "/data/W2NER/main.py", line 299, in <module>
    trainer.train(i, train_loader)
  File "/data/W2NER/main.py", line 75, in train
    label_result = torch.cat(label_result)
RuntimeError: torch.cat(): expected a non-empty list of Tensors

**Comment by ljynlp** [comment]
ADR means adverse drug reactions, you can find the detailed description in [Cadec: A corpus of adverse drug event annotations](https://www.sciencedirect.com/science/article/pii/S1532046415000532).
The example is only for demostrating data structure, please replace it with one dataset in this [link](https://drive.google.com/drive/folders/1NdvUeIUUL3mlS8QwwnqM628gCK7_0yPv?usp=sharing).
